### PR TITLE
Email verification

### PR DESCRIPTION
**Pull request by mustafaMohd**

### CODE REVIEW

**Review by tushar-bacancy — APPROVED** [review]

**Comment by hagopj13** [comment]
Closes #77

**Comment by hagopj13** [comment]
@mustafaMohd thanks for the contribution. I will do minor modifications on it.

**Comment by mustafaMohd** [comment]
I am really impressed by work of all contributors especially @hagopj13 I have no words for appreciation.

**Comment by mustafaMohd** [comment]
@tushar-bacancy.. Thanks for approval. 👍👍👍

**Comment by hagopj13** [comment]
@mustafaMohd your contribution was equally impressive and appreciated!

**Comment by mustafaMohd** [comment]
Thanks @hagopj13 👍👍👍.

**Pull request merged**
