### PR TITLE
Paginate Plugin fixed

### PR DESCRIPTION
**Pull request by Salman9000**
Added Readme for paginate

### CODE REVIEW

**Comment by trasherdk** [comment]
There's a mismatch between `yarn.lock`, `package-lock.json` and `package.json` that need fixing.

Doing a `rm -fr node_modules && npm ci` probably fixes that. Don't forget to push the lock files too.

**Comment by trasherdk** [comment]
The checks are failing because the `yarn.lock` file has not been updated.

I'm using `node 14.16.1` and `npm 7.10` and running `npm ci` or `npm update` will update both lock-files.

```sh
$ yarn --frozen-lockfile

yarn install v1.22.4

warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

[1/5] Validating package.json...

[2/5] Resolving packages...

ongoose-paginate-v2@^1.3.17ongoose-paginate-v2@^1.3.17ongoose-paginate-v2@^1.3.17ongoose-paginate-v2@^1.3.17ongoose-paginate-v2@^1.3.17ongoose-paginate-v2@^1.3.17ongoose-paginate-v2@^1.3.17ongoose-paginate-v2@^1.3.17ongoose-paginate-v2@^1.3.17error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by trasherdk** [comment]
Okay. I give up.

**Comment by Salman9000** [comment]
I give up.

**Comment by hagopj13** [comment]
Hi @Salman9000 and @trasherdk. Sorry for the late response on this. Thank you both for your contributions.

@Salman9000 I see that you created this pull request to solve #106. The boilerplate is not using any external packages for the paginate plug in. What it is actually using is a custom plugin that I've created. We can surely extend that to support more features. That explains why tests were failing.

Let's take it over to the issue (#106 ) and we can discuss potential improvements to the existing plugin there.

**Pull request closed without merging**
