### PR TITLE
Removed unused spaces in sendResetPasswordEmail text

### PR DESCRIPTION
**Pull request by mddarmawan**

### CODE REVIEW

**Review by hagopj13 — APPROVED** [review]

**Comment by mddarmawan** [comment]
Thanks!

**Comment by mddarmawan** [comment]
Before:
image

After:
image

**Comment by hagopj13** [comment]
Good one! Thanks.

**Comment by mddarmawan** [comment]
My pleasure! Thanks for such a great repo. I am using it for my project. And if it already started to get profits, will back to you :)

**Comment by hagopj13** [comment]
I'm glad you like it and find it useful. And if you feel like it can be improved in any way, then please feel free to contribute.

**Comment by mddarmawan** [comment]
Absolutely will do.

**Comment by mddarmawan** [comment]
Have another question, still regarding the password reset. I have encountered with `TokenExpiredError` but I can't see there are any exception to handle that, just `Password reset failed` message.

Logs:
image

My workaround is:
image

Should I do a PR?

**Comment by hagopj13** [comment]
This looks nice. You can submit a PR. Also, please add an assertion for the error message in the corresponding test case.

**Pull request merged**
