### PR TITLE
Added support for populate data

### PR DESCRIPTION
**Pull request by samkit5495**

### CODE REVIEW

**Review by paladosss — COMMENTED** [review]
Good

**Comment by hagopj13** [comment]
Hi @samkit5495 thank you for the PR. The implementation looks great. Can you also add test cases for it?

**Comment by samkit5495** [comment]
Hi @hagopj13 I have added a test case for it

**Comment by hagopj13** [comment]
Hi @samkit5495 thanks for the change. Although the test is legit, it involves changing the model for the user, but adding manager field to a user doesn't really make much sense for a boilerplate.

I suggest you revert the last commit, and then I'll merge only the implementation code of populate, and add the tests later on.

**Comment by samkit5495** [comment]
@hagopj13 reverted the commit

**Review by hagopj13 — APPROVED** [review]

**Pull request merged**
