### PR TITLE
log every request info

### PR DESCRIPTION
**Pull request by lifefloating**
hi， i wrote some code to implement the function of log each request info, for log view

### CODE REVIEW

**Comment by lifefloating** [comment]
@hagopj13

**Comment by hagopj13** [comment]
@lifefloating thanks for you contribution.

The boilerplate already has request logging (check `src/config/morgan.js`). Does what you have here add anything special on top of that? Please let me know

**Comment by lifefloating** [comment]
> @lifefloating thanks for you contribution.
> 
> The boilerplate already has request logging (check `src/config/morgan.js`). Does what you have here add anything special on top of that? Please let me know.

i didn't notice morgan，sry.   all of them works

**Comment by hagopj13** [comment]
@lifefloating no worries. Thanks again!

**Pull request closed without merging**
